src/objects/Stripe_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Is_Live_Environment__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this to use the LIVE key in all API operations.</inlineHelpText>
        <label>Is Live Environment</label>
        <type>Checkbox</type>
    </fields>
    <label>Stripe Settings</label>
</CustomObject>

src/classes/StripeAPI.cls
global class StripeAPI {

	global static String ApiKey {
		get {
			Stripe_Settings__c s = Stripe_Settings__c.getInstance();
			if (s != null) {
				if (StripeAPI.isTest) {
					return s.Stripe_Test_Key__c;
				} else {
					return s.Stripe_Live_Key__c;
				}
			}
			return null;
		}
	}
	
	global static Boolean isTest {
		get {
			Stripe_Settings__c s = Stripe_Settings__c.getInstance();
			if (s != null) {
				return !s.Is_Live_Environment__c;
			}
			return true;
		}
	}
	
}