src/objects/Stripe_Webhook__c.object
<CustomObject>
    <description>Records created to assist with the processing of delayed webhooks from stripe.</description>
    <fields>
        <fullName>Attempts__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>Number of attempts made at processing this webhook</inlineHelpText>
        <label>Attempts</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Succeeded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Webhook_Data__c</fullName>
        <label>Webhook Data</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Webhook_Type__c</fullName>
        <label>Webhook Type</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Stripe Webhook</label>
    <nameField>
        <displayFormat>HK-{00000}</displayFormat>
        <label>Stripe Webhook #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Webhooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WebhookDelayedProcessor.cls
global class WebhookDelayedProcessor implements Database.Batchable<sObject> {
	
	private Boolean reschedule = false;
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator([
			Select Id, Webhook_Type__c, Webhook_Data__c, Attempts__c From Stripe_Webhook__c
				Where Status__c = 'Pending'
		]);
	}

 	global void execute(Database.BatchableContext BC, List<Stripe_Webhook__c> webhooks) {
		for (Stripe_Webhook__c webhook : webhooks) {
			webhook.Attempts__c += 1;
			System.debug(System.LoggingLevel.INFO, '\n**** Webhook: '+webhook); 

			if (webhook.Webhook_Type__c == 'charge.succeeded') {
				StripeCharge charge = (StripeCharge) JSON.deserialize(webhook.Webhook_Data__c, StripeCharge.class);
				StripeWebhookListener listener = new StripeWebhookListener();
				
				try {
					listener.handle_ChargeSucceeded(charge, false);
					webhook.Status__c = 'Succeeded';
				} catch (WebhookDelayedProcessor.WebhookDelayedProcessorException e) {
					if (webhook.Attempts__c >= 3) {
						webhook.Status__c = 'Failed';
					}
					reschedule = true;
				}
			}
		}
		
		update webhooks;		
	}
	
	global void finish(Database.BatchableContext BC) {
		if (reschedule) {
			StripeAPI.startWebhookProcessor();
		}
	}
	
	global class WebhookDelayedProcessorException extends System.Exception {}

}